-- Convert media and referencing IDs to integers/identity

-- media_files.id -> integer identity
ALTER TABLE "media_files"
  ALTER COLUMN "id" TYPE integer USING "id"::integer,
  ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;

-- blog_posts cover/og media references -> integer
ALTER TABLE "blog_posts"
  ALTER COLUMN "cover_media_id" TYPE integer USING NULLIF("cover_media_id", '')::integer,
  ALTER COLUMN "og_image_media_id" TYPE integer USING NULLIF("og_image_media_id", '')::integer;

-- blog_authors avatar reference -> integer
ALTER TABLE "blog_authors"
  ALTER COLUMN "avatar_media_id" TYPE integer USING NULLIF("avatar_media_id", '')::integer;

-- site_settings logo/default OG references -> integer
ALTER TABLE "site_settings"
  ALTER COLUMN "logo_media_id" TYPE integer USING NULLIF("logo_media_id", '')::integer,
  ALTER COLUMN "default_og_image_id" TYPE integer USING NULLIF("default_og_image_id", '')::integer;
